### ISSUE TITLE
Doesn't convert

### ISSUE THREAD

**Issue by Doogls** [REDxEYE/Source2Converter#6]
After selecting the target folder. After selecting a folder with both models and models and materials of the first source - an error

Traceback (most recent call last):
  File "H:\Source2Converter-0.8\convert_model.py", line 254, in <module>
    vmdl_file = convert_model(glob_file, output_folder, args.sbox, args.with_flex_rules)
  File "H:\Source2Converter-0.8\convert_model.py", line 57, in convert_model
    model_decompiler = ModelDecompiler(s1_model)
  File "H:\Source2Converter-0.8\SourceIO\library\source1\dmx\source1_to_dmx.py", line 420, in __init__
    self.mdl = MdlV49(self.mdl_file)
TypeError: MdlV49.__init__() missing 16 required positional arguments: 'bones', 'skin_groups', 'materials', 'materials_paths', 'flex_names', 'flex_controllers', 'flex_ui_controllers', 'flex_rules', 'body_parts', 'attachments', 'anim_descs', 'sequences', 'animations', 'key_values_raw', 'key_values', and 'include_models'

**Comment by REDxEYE** [comment]
Download repositories of both projects instead of releases and use convert_model_v2.py instead of old one

**Comment by Doogls** [comment]
All downloaded from the attached repository. I use the instructions from the ReadMe

**Comment by REDxEYE** [comment]
You are using 0.8 release instead of master commit

**Comment by Doogls** [comment]
Error when i using convert_model_v2.py

Traceback (most recent call last):
  File "H:\Source2Converter-0.8\convert_model_v2.py", line 9, in <module>
    from SourceIO.library.source1.dmx.source1_to_dmx import DmxModel2, get_slice
ImportError: cannot import name 'DmxModel2' from 'SourceIO.library.source1.dmx.source1_to_dmx' (H:\Source2Converter-0.8\SourceIO\library\source1\dmx\source1_to_dmx.py)

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/Source2Converter/archive/refs/heads/master.zip
https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by REDxEYE** [comment]
Try with this version, they should work together

**Comment by Doogls** [comment]
Yes, after downloading everything from these links, everything worked, please update the ReadME. Thank you

**Comment by REDxEYE** [comment]
I'm working on the new release. It should address all the setup issues

**Comment by Doogls** [comment]
It will be great!)
