### ISSUE TITLE
Source 2 Converter cannot convert my models

### ISSUE THREAD

**Issue by Zaptyp** [REDxEYE/Source2Converter#7]
`[INFO]--[ContentManager:find_file] Requesting C:\Users\Zaptyp\Desktop\SOURCE 2\SOURCE 1 MATERIALS\models\models\rising_threat\mopw_storage_suit_cabinet.vvd file
[DEBUG]--[ContentManager:find_file] Found in SOURCE 1 MATERIALS!
[INFO]--[ContentManager:find_file] Requesting C:\Users\Zaptyp\Desktop\SOURCE 2\SOURCE 1 MATERIALS\models\models\rising_threat\mopw_storage_suit_cabinet.dx90.vtx file
[DEBUG]--[ContentManager:find_file] Found in SOURCE 1 MATERIALS!
[INFO]--[ContentManager:find_file] Requesting materials\IW\Rising_Threat\storage_suit_cabinet_c.vmt file
[DEBUG]--[ContentManager:find_file] Found in SOURCE 1 MATERIALS!
[INFO]--[ContentManager:find_file] Requesting materials\IW\Rising_Threat\oilrig_hanging_jumpsuit_fac_col.vmt file
[DEBUG]--[ContentManager:find_file] Found in SOURCE 1 MATERIALS!
Decompiling model "models\iw\rising_threat\mopw_storage_suit_cabinet.mdl"
        Generating DMX file for "mopw_storage_suit_cabinet.smd" mesh
        Generating DMX file for "mopw_mtl_sov_hanging_jumpsuit_fac.smd" mesh
Converting materials
        Converting "storage_suit_cabinet_c"
Traceback (most recent call last):
  File "C:\Users\Zaptyp\Desktop\Source2Converter\convert_model.py", line 292, in <module>
    vmdl_file = convert_mdl(glob_file, output_folder, args.sbox)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zaptyp\Desktop\Source2Converter\convert_model.py", line 237, in convert_mdl
    result, error_message = convert_material(mat, s2_output_path, sbox_mode)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zaptyp\Desktop\Source2Converter\material_converter.py", line 32, in convert_material
    vmt = VMT(material[2], material[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zaptyp\Desktop\Source2Converter\SourceIO\library\source1\vmt\__init__.py", line 20, in __init__
    parser.parse()
  File "C:\Users\Zaptyp\Desktop\Source2Converter\SourceIO\library\utils\kv_parser.py", line 393, in parse
    raise KVParserException(
SourceIO.library.utils.kv_parser.KVParserException: Unexpected token VKVToken.LBRACKET:"[" in storage_suit_cabinet_c at 12:30`
I running on python 3.11.4

**Comment by REDxEYE** [comment]
It tells you that something went wrong during parsing of storage_suit_cabinet_c vmt file
It got an unexpected token there, check the file, it may be malformed
