### ISSUE TITLE
Failed to compile models

### ISSUE THREAD

**Issue by RusJJ** [REDxEYE/Source2Converter#8]
```
[INFO]--[ContentManager:find_file] Requesting C:\cs2import\csgo\models\porch_trim_129.vvd file
[INFO]--[ContentManager:find_file] Requesting C:\cs2import\csgo\models\porch_trim_129.dx90.vtx file
[INFO]--[ContentManager:find_file] Requesting materials\models\porchpillar.vmt file
Decompiling model "models\porch_trim_129.mdl"
        Generating DMX file for "porch_trim_129.smd" mesh
Converting materials
        Converting "porchpillar"
[INFO]--[VertexLitGeneric:load_texture] Loading texture models/porchpillar
[INFO]--[ContentManager:find_file] Requesting materials\models\porchpillar.vtf file
[INFO]--[VertexLitGeneric:write_texture] Wrote texture to C:\cs2import\game\csgo_addons\myaddon\materials\models\porchpillar_color.tga
ResourceCompiler Detected
Compiling model: C:\cs2import\game\csgo_addons\enterprise_port\models\porch_trim_129.vmdl
Creating device for graphics adapter 0 'NVIDIA GeForce RTX 4060 Ti' [vendorid 0x10DE]: 31.0.15.4584
FS:  Tried to FileExists NULL filename!
File "" doesn't exist!

-----------------------------------------------------------------
 ERROR: 0 compiled, 1 failed, 0 skipped, 0m:00s
-----------------------------------------------------------------
```

**Comment by REDxEYE** [comment]
Not sure what caused that error. But your cs2 addon folder must be in game's content folder
`Counter-Strike Global Offensive\content\csgo_addons\<ADDON_NAME>` not a random folder

**Comment by REDxEYE** [comment]
Compilation is optional process. Model will be compiled by game automatically

**Comment by RusJJ** [comment]
> Not sure what caused that error. But your cs2 addon folder must be in game's content folder
> `Counter-Strike Global Offensive\content\csgo_addons\<ADDON_NAME>` not a random folder

That's the game content folder. Hardlinked it before for dumb import scripts by Valve... If it's gonna work without compilation, alright then. I will continue it, thanks!

**Comment by RusJJ** [comment]
As a bonus, one of VMT files are referring to a missing VTF file. The progress just stopped with a message: 
![image](https://github.com/REDxEYE/Source2Converter/assets/8864329/1cf44d8e-634b-4bcf-b40b-f5cfa2ba7044)

P.S. If im not wrong, happened here: https://github.com/REDxEYE/Source2Converter/blob/6cedd2880e7cb3e34929845ad25dcbc27e87f4af/material_converter.py#L31

**Comment by RusJJ** [comment]
Closing this as it's fixed now. The problem was in my inattention: "Addon Folder" was the wrong one **not from content**.
Leave a note in README for that please, for the future problems LOL
